#!/usr/bin/env bash

# autoinstall – Tool for installing software package from source with minimal effort
# 
# Copyright © 2012  Mattias Andrée (maandree@kth.se)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


success=1

if [[ -f "setup" ]]; then
    chmod a+rx "setup"
    ./"setup" install || ./"setup" || success=0
elif [[ -f "setup.pl" ]]; then
    chmod a+rx "setup.pl"
    ./"setup.pl" install || ./"setup.pl" || success=0
elif [[ -f "setup.py" ]]; then
    chmod a+rx "setup.py"
    ./"setup.py" install || ./"setup.py" || success=0
elif [[ -f "setup.sh" ]]; then
    chmod a+rx "setup.sh"
    ./"setup.sh" install || ./"setup.sh" || success=0
elif [[ -f "install" ]]; then
    chmod a+rx "install"
    ./"install" install || ./"install" || success=0
elif [[ -f "install.pl" ]]; then
    chmod a+rx "install.pl"
    ./"install.pl" install || ./"install.pl" || success=0
elif [[ -f "install.py" ]]; then
    chmod a+rx "install.py"
    ./"install.py" install || ./"install.py" || success=0
elif [[ -f "install.sh" ]]; then
    chmod a+rx "install.sh"
    ./"install.sh" install || ./"install.sh" || success=0
else
    if [[ ! -f "Makefile" ]] && [[ ! -f "makefile" ]]; then
        if [[ ! -f "configure" ]] && [[ ! -f "configure.sh" ]]; then
            if [[ ! -f "autogen" ]] && [[ ! -f "autogen.sh" ]]; then
                if [[ -f "bootstrap.sh" ]]; then
                    chmod a+rx "bootstrap.sh"
                    ./"bootstrap.sh" || success=0
                elif [[ -f "bootstrap" ]]; then
                    chmod a+rx "bootstrap"
                    ./"bootstrap" || success=0
                else
                    success=0
                fi
            fi
            if [[ $success = 1 ]]; then
                if [[ -f "autogen.sh" ]]; then
                    chmod a+rx "autogen.sh"
                    ./"autogen.sh" || success=0
                elif [[ -f "autogen" ]]; then
                    chmod a+rx "autogen"
                    ./"autogen" || success=0
                else
                    success=0
                fi
            fi
        fi
        if [[ $success = 1 ]]; then
            if [[ -f "configure.sh" ]]; then
                chmod a+rx "configure.sh"
                ./"configure.sh" || success=0
            elif [[ -f "configure" ]]; then
                chmod a+rx "configure"
                ./"configure" || success=0
            else
                success=0
            fi
        fi
    fi
    if [[ $success = 1 ]]; then
        if [[ -f "Makefile" ]] || [[ -f "makefile" ]]; then
            (make -B && make -B install) || success=0
        else
            success=0
        fi
    fi
if

[[ $success = 0 ]] &&
    echo -e '\e[1;31m::\e[39mDo not know how to install, please help...\e[21m'

exit $(( 1 - $success ))
