#!/usr/bin/env bash

success=1

if [[ ! -f "Makefile" ]] && [[ ! -f "makefile" ]]; then
    if [[ ! -f "configure" ]] && [[ ! -f "configure.sh" ]]; then
	if [[ ! -f "autogen" ]] && [[ ! -f "autogen.sh" ]]; then
	    if [[ -f "bootstrap.sh" ]]; then
		chmod a+rx "bootstrap.sh"
		./"bootstrap.sh" || success=0
	    elif [[ -f "bootstrap" ]]; then
		chmod a+rx "bootstrap"
		./"bootstrap" || success=0
	    else
		success=0
	    fi
	fi
	if [[ $success = 1 ]]; then
	    if [[ -f "autogen.sh" ]]; then
		chmod a+rx "autogen.sh"
		./"autogen.sh" || success=0
	    elif [[ -f "autogen" ]]; then
		chmod a+rx "autogen"
		./"autogen" || success=0
	    else
		success=0
	    fi
	fi
    fi
    if [[ $success = 1 ]]; then
	if [[ -f "configure.sh" ]]; then
	    chmod a+rx "configure.sh"
	    ./"configure.sh" || success=0
	elif [[ -f "configure" ]]; then
	    chmod a+rx "configure"
	    ./"configure" || success=0
	else
	    success=0
	fi
    fi
fi
if [[ $success = 1 ]]; then
    if [[ -f "Makefile" ]] || [[ -f "makefile" ]]; then
	(make -B && make -B install) || success=0
    else
	success=0
    fi
fi

[[ $success = 0 ]] &&
    echo -e '\e[1;31m::\e[39mDo not know how to install, please help...\e[21m'

exit $(( 1 - $success ))
